name: forge2d
version: 0.8.0
description: A 2D physics engine for Dart, also works with the Flame game engine in Flutter
homepage: https://github.com/flame-engine/forge2d

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: '>=2.1.0 <3.0.0'
