name: forge2d
version: 0.6.2
description: A 2D physics engine for Dart, also works with the Flame game engine in Flutter
homepage: https://github.com/flame-engine/forge2d
dependencies:
  vector_math: '>=2.0.0 <3.0.0'
dev_dependencies:
  build_web_compilers: ^2.12.0-dev.1
  build_runner: ^1.6.2
environment:
  sdk: ">=2.3.0 <3.0.0"
