name: forge2d_benchmark
description: Simple benchmark for Forge2D

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build_runner: ^2.4.5
  build_web_compilers: ^4.0.3
  forge2d: ^0.11.0

dev_dependencies:
  flame_lint: ^0.2.0
