name: forge2d_examples
description: Samples showcasing Forge2D

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  forge2d: ^0.12.0

dev_dependencies:
  build_runner: ^2.4.5
  build_web_compilers: ^4.0.4
  flame_lint: ^1.1.1
