name: forge2d_examples
description: Samples showcasing Forge2D
version: 1.0.0+1
resolution: workspace

publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  forge2d: ^0.14.1
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.6.0
  build_web_compilers: ^4.2.0
  flame_lint: ^1.4.1
