name: forge2d
version: 0.11.0
description: A 2D physics engine for Dart (based on Box2D), also works with the Flame game engine in Flutter
homepage: https://github.com/flame-engine/forge2d

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  vector_math: ">=2.1.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.20.1
  flame_lint: ^0.1.0
  dartdoc: ^5.0.1
