name: forge2d
version: 0.12.2
description: A 2D physics engine for Dart (based on Box2D), also works with the Flame game engine in Flutter
homepage: https://github.com/flame-engine/forge2d

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  vector_math: ^2.1.4

dev_dependencies:
  dartdoc: ^7.0.2
  flame_lint: ^1.1.1
  mocktail: ^1.0.1
  test: any
