name: forge2d
version: 0.14.0
description: A 2D physics engine for Dart (based on Box2D), also works with the Flame game engine in Flutter
homepage: https://github.com/flame-engine/forge2d
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  vector_math: ^2.2.0
  web: ^1.1.1

dev_dependencies:
  dartdoc: ^8.3.4
  flame_lint: ^1.4.1
  mocktail: ^1.0.4
  test: ^1.26.3
